# Generated by Django 4.2 on 2026-02-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='average_package',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average package in LPA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='highest_package',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Highest package in LPA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_description',
            field=models.TextField(blank=True, help_text='Details about placement statistics and companies.', null=True),
        ),
    ]
