# Generated by Django 5.2.11 on 2026-02-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_average_package_college_highest_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('classroom', 'Classroom'), ('campus', 'Campus'), ('library', 'Library'), ('hostel', 'Hostel'), ('canteen', 'Canteen'), ('seminar_hall', 'Seminar Hall'), ('ground', 'Ground'), ('laboratory', 'Laboratory'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='gallery/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_media', to='colleges.college')),
            ],
        ),
    ]
